export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ADD_EXERCISE_WITH_TITLE = 'ADD_EXERCISE_WITH_TITLE';
export const WORKOUT_NAME_CHANGED = 'WORKOUT_NAME_CHANGED';
export const WORKOUT_DATE_CHANGED = 'WORKOUT_DATE_CHANGED';
export const CLEAR_WORKOUT_INPUT = 'CLEAR_WORKOUT_INPUT';
export const ADD_SET = 'ADD_SET';
export const SAVE_NEW_SET = 'SAVE_NEW_SET';
export const SAVE_EXERCISE_TITLE = 'SAVE_EXERCISE_TITLE';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const WEIGHT_CHANGED = 'WEIGHT_CHANGED';
export const REPETITIONS_CHANGED = 'REPETITIONS_CHANGED';
export const COMMENT_CHANGED = 'COMMENT_CHANGED';
export const SHOW_SET_FORM = 'SHOW_SET_FORM';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT';
export const REMOVE_SET = 'REMOVE_SET';